SET IDENTITY_INSERT [dbo].[TransactionTypes] ON
INSERT INTO [dbo].[TransactionTypes] ([Id], [Name], [EntryTypeId]) VALUES (1, N'Cash and cash equivalents', 1)
INSERT INTO [dbo].[TransactionTypes] ([Id], [Name], [EntryTypeId]) VALUES (2, N'Inventory', 1)
INSERT INTO [dbo].[TransactionTypes] ([Id], [Name], [EntryTypeId]) VALUES (3, N'PPE (Property, Plant, and Equipment)', 1)
INSERT INTO [dbo].[TransactionTypes] ([Id], [Name], [EntryTypeId]) VALUES (5, N'Land', 1)
INSERT INTO [dbo].[TransactionTypes] ([Id], [Name], [EntryTypeId]) VALUES (6, N'Buildings', 1)
INSERT INTO [dbo].[TransactionTypes] ([Id], [Name], [EntryTypeId]) VALUES (7, N'Furniture', 1)
INSERT INTO [dbo].[TransactionTypes] ([Id], [Name], [EntryTypeId]) VALUES (8, N'Patents', 1)
INSERT INTO [dbo].[TransactionTypes] ([Id], [Name], [EntryTypeId]) VALUES (9, N'Common Stock', 1)
INSERT INTO [dbo].[TransactionTypes] ([Id], [Name], [EntryTypeId]) VALUES (10, N'Equipment', 1)
INSERT INTO [dbo].[TransactionTypes] ([Id], [Name], [EntryTypeId]) VALUES (11, N'Others', 1)
INSERT INTO [dbo].[TransactionTypes] ([Id], [Name], [EntryTypeId]) VALUES (12, N'Personal', 1)
INSERT INTO [dbo].[TransactionTypes] ([Id], [Name], [EntryTypeId]) VALUES (13, N'Accounts payable', 2)
INSERT INTO [dbo].[TransactionTypes] ([Id], [Name], [EntryTypeId]) VALUES (14, N'Interest payable', 2)
INSERT INTO [dbo].[TransactionTypes] ([Id], [Name], [EntryTypeId]) VALUES (15, N'Income taxes payable', 2)
INSERT INTO [dbo].[TransactionTypes] ([Id], [Name], [EntryTypeId]) VALUES (16, N'Bills payable', 2)
INSERT INTO [dbo].[TransactionTypes] ([Id], [Name], [EntryTypeId]) VALUES (17, N'Bank account overdrafts', 2)
INSERT INTO [dbo].[TransactionTypes] ([Id], [Name], [EntryTypeId]) VALUES (18, N'Accrued expenses', 2)
INSERT INTO [dbo].[TransactionTypes] ([Id], [Name], [EntryTypeId]) VALUES (19, N'Short-term loans', 2)
INSERT INTO [dbo].[TransactionTypes] ([Id], [Name], [EntryTypeId]) VALUES (20, N'Capital Expenditure', 3)
INSERT INTO [dbo].[TransactionTypes] ([Id], [Name], [EntryTypeId]) VALUES (21, N'Revenue Expenditure', 3)
INSERT INTO [dbo].[TransactionTypes] ([Id], [Name], [EntryTypeId]) VALUES (22, N'Normal goods Purchase or Expenditure', 3)
INSERT INTO [dbo].[TransactionTypes] ([Id], [Name], [EntryTypeId]) VALUES (23, N'Earned Income', 4)
INSERT INTO [dbo].[TransactionTypes] ([Id], [Name], [EntryTypeId]) VALUES (24, N'Portfolio Income', 4)
INSERT INTO [dbo].[TransactionTypes] ([Id], [Name], [EntryTypeId]) VALUES (25, N'active income', 4)
INSERT INTO [dbo].[TransactionTypes] ([Id], [Name], [EntryTypeId]) VALUES (26, N'Sales', 4)
SET IDENTITY_INSERT [dbo].[TransactionTypes] OFF
